version: '3'
services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      RAILS_ENV: ${ENVIRONMENT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      API_TOKEN: ${API_TOKEN}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"

  mailhog:
    image: mailhog/mailhog
    depends_on:
      - web
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db-data-postgres:
    driver: local